---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Jordan Stuecken"
pagetitle: "L01 Jordan Stuecken"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Stuecken GitHub Repo](https://github.com/stat301-3-2026-spring/l01-review-jordanstuecken)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

1. splitting data into training and testing sets (and potentially creating resamples like v-folds)
2. creating recipes to preprocess and transform the data
3. defining workflows (model type, recipe, data, and potential tuning parameters)
4. tuning/selecting the best parameters using resampling on training data
5. fitting the final model on the training data and evaluating performance on the testing data

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning has a target variable of interest that the model is trying to predict. The outcome variable supervises the process by providing a correct answer to compare predictions against.

Unsupervised learning does not have a specific target variable and instead looks for patterns within a full set of unlabeled data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A descriptive model describes characteristics or relationships within data through summaries or visualizations (such as geom_smooth() function). The goal is to understand the general structure and trends in the data.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

An inferential model tests a hypothesis or research question. It is used to understand how one variable impacts another, focusing on estimating relationships between variables in a dataset.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

A predictive model uses patterns in existing data to predict outcomes for unseen data points.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model follows a known parametric equation to relate an outcome with predictors. This model type is usually easier to interpret and requires less data, but has limited complexity and flexibility.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model makes fewer assumptions about the relationship between variables and uses the observed data to learn patterns. While more flexible, this model type can be more prone to overfitting and typically takes more time to run.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Parametric models are generally mechanistic, as they assume a specific guiding function. Nonparametric models are generally empirically driven and allow the data to determine the structure of the model.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is easier to interpret because it follows a known equation and is typically less complex than an empirically driven model that may be harder to interpret.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.


::: {.callout-tip icon="false"}
## Solution

Mechanistic models are less flexible because they follow a predefined formula.

Empirically driven models are more flexible because they allow the data to determine the model.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to have higher bias and lower variance because they make stronger assumptions about the data.

Empirically driven models tend to have lower bias but higher variance, as they fit the data more closely and may overfit.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression problems predict a numerical outcome value based on predictor variables. Classification problems predict the class of the categorical outcome variable along with a confidence level in its prediction.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

When splitting data, it is useful to stratify by the outcome/target variable to ensure that each split has a similar distribution of the outcome. This helps ensure that all classes or ranges of the outcome are thoroughly represented, leading to a more accurate model fit.
:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation divides the data into V folds and uses V-1 as training data with the remaining fold as the test set, and then repeats the process so that each fold serves as the test set once. The process is then repeated a specified number of times. RMSE is calculated for each fold, and the average RMSE across all folds and repeats is used as an estimate of test error. We use this process to get a more reliable estimate of model performance while reducing dependence on a single train/test split to lower the risk of overfitting.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling may be preferred over v-fold to estimate test RMSE when working with a smaller dataset where splitting the data into several folds may not allow for sufficient data to train a model. Bootstrapping allows for repeated sampling with replacement to make use of more of the available data.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning estimates model performance on a specified range and number of hyperparameters for each model type. This process allows the optimal parameters for a model to be identified, as well as compare performance across models with best parameters selected.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE, MAE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy, ROC AUC

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential: This question asks if there exists a relationship between number of service calls and likelihood of churn. Inferential models such as this example answer a research question about how variables in a dataset relate to eachother.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Predictive: this question asks for a specific estimate of a customer's likelihood to churn based on predictor variables. This is a classification problem, where customers are classified into churn or non-churn with associated probabilities.

:::

